### ISSUE TITLE
Reanimated 2

### ISSUE THREAD

**Issue by nandorojo** [felippepuhle/react-native-reanimated-confetti#18]
Hey, sorry to dig up an old library, but just wondering if anyone has moved this to Reanimated 2? Looks like it would be fairly simple.

**Comment by felippepuhle** [comment]
Yeah sorry as I'm not using such animation anymore I didn't have time to maintain it...

There's a [fork](https://github.com/elmotan95/react-native-reanimated-confetti) that apparently did that though, maybe you can try that one?
