### ISSUE TITLE
it have error 

### ISSUE THREAD

**Issue by TranPhuc9898** [felippepuhle/react-native-reanimated-confetti#21]
![simulator_screenshot_5F5E562F-521C-4337-A9C9-BA4B1BF7E1C1](https://user-images.githubusercontent.com/57553531/208631796-c8bbcb4b-dce1-4480-b61b-b99c2d34f9a3.png)

**Comment by felippepuhle** [comment]
Please note this repo is 3 years old and it didn't receive any updates, by the time it was created reanimated 2 didn't even exist, maybe trying [this fork](https://github.com/elmotan95/react-native-reanimated-confetti) can help
